-- RetroOnto Database Schema
-- SQLite with FTS5 full-text search

-- Decision traces (E0-E4)
CREATE TABLE IF NOT EXISTS decision_traces (
    id TEXT PRIMARY KEY,
    e0_raw_event TEXT NOT NULL,
    e1_classification TEXT NOT NULL,
    e2_derivation_chain TEXT,
    e3_resolution TEXT,
    e4_encoded_rule TEXT,
    source_agent TEXT,
    category TEXT NOT NULL CHECK(category IN ('infrastructure', 'coordination', 'cognitive')),
    severity TEXT CHECK(severity IN ('🔴', '🟡', '🟢')),
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'superseded', 'archived')),
    created_at TEXT DEFAULT (datetime('now')),
    verified_by TEXT
);

-- Full-text search index
CREATE VIRTUAL TABLE IF NOT EXISTS decision_traces_fts USING fts5(
    id UNINDEXED,
    e0_raw_event,
    e1_classification,
    e2_derivation_chain,
    e3_resolution,
    e4_encoded_rule,
    content='decision_traces',
    content_rowid='rowid'
);

-- Triggers to keep FTS in sync
CREATE TRIGGER IF NOT EXISTS decision_traces_ai AFTER INSERT ON decision_traces BEGIN
    INSERT INTO decision_traces_fts(rowid, id, e0_raw_event, e1_classification, e2_derivation_chain, e3_resolution, e4_encoded_rule)
    VALUES (new.rowid, new.id, new.e0_raw_event, new.e1_classification, new.e2_derivation_chain, new.e3_resolution, new.e4_encoded_rule);
END;

-- Constraint rules (generated by constraint-gen)
CREATE TABLE IF NOT EXISTS constraints (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    rule_type TEXT CHECK(rule_type IN ('executable', 'manual', 'pattern')),
    source_trace_id TEXT,
    severity TEXT CHECK(severity IN ('🔴', '🟡', '🟢')),
    check_command TEXT,
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'disabled', 'deprecated')),
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (source_trace_id) REFERENCES decision_traces(id)
);

-- Knowledge ring writeback log
CREATE TABLE IF NOT EXISTS writebacks (
    id TEXT PRIMARY KEY,
    source_trace_id TEXT NOT NULL,
    target_path TEXT NOT NULL,
    constraint_id TEXT,
    success INTEGER DEFAULT 1,
    written_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (source_trace_id) REFERENCES decision_traces(id),
    FOREIGN KEY (constraint_id) REFERENCES constraints(id)
);

-- Founder directives (for gate collision detection)
CREATE TABLE IF NOT EXISTS directives (
    id TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    scope TEXT,
    trigger_keywords TEXT,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT (datetime('now'))
);

-- Archive entries (filesystem-backed, metadata here)
CREATE TABLE IF NOT EXISTS archive_entries (
    id TEXT PRIMARY KEY,
    type TEXT CHECK(type IN ('error', 'success')),
    category TEXT CHECK(category IN ('infrastructure', 'coordination', 'cognitive')),
    file_path TEXT,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT (datetime('now'))
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_traces_category ON decision_traces(category);
CREATE INDEX IF NOT EXISTS idx_traces_severity ON decision_traces(severity);
CREATE INDEX IF NOT EXISTS idx_traces_status ON decision_traces(status);
CREATE INDEX IF NOT EXISTS idx_constraints_status ON constraints(status);
