#!/usr/bin/env bash
# retroonto-trace — Capture a decision event → Archive + DB + Broadcast
# Usage: ./src/trace.sh --type error|success --category infrastructure|coordination|cognitive [options]
set -euo pipefail

RETROONTO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ARCHIVE_DIR="${RETROONTO_DIR}/archive"
DB="${RETROONTO_DIR}/retroonto.db"

# Parse args
TYPE=""
CATEGORY=""
DESC=""
SEVERITY="🟡"
AGENT="unknown"
VERIFIED_BY=""
OUTPUT_ONLY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --type) TYPE="$2"; shift 2 ;;
        --category) CATEGORY="$2"; shift 2 ;;
        --desc) DESC="$2"; shift 2 ;;
        --severity) SEVERITY="$2"; shift 2 ;;
        --agent) AGENT="$2"; shift 2 ;;
        --verified-by) VERIFIED_BY="$2"; shift 2 ;;
        --output-only) OUTPUT_ONLY=true; shift ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

if [[ -z "$TYPE" || -z "$CATEGORY" || -z "$DESC" ]]; then
    echo "Usage: $0 --type error|success --category infrastructure|coordination|cognitive --desc \"description\" [--severity 🔴|🟡|🟢] [--agent name] [--verified-by name]"
    exit 1
fi

# Generate ID
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
ID="${TYPE:0:3}-${TIMESTAMP}"
ARCHIVE_FILE="${ARCHIVE_DIR}/${TYPE}s/${CATEGORY}/${ID}.md"

# Ensure archive directory exists
mkdir -p "${ARCHIVE_DIR}/${TYPE}s/${CATEGORY}"

# Create archive entry
cat > "$ARCHIVE_FILE" << EOF
---
id: ${ID}
type: ${TYPE}
category: ${CATEGORY}
severity: ${SEVERITY}
status: active
created: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
source_agent: ${AGENT}
verified_by: ${VERIFIED_BY}
---

# ${ID}: ${DESC}

## Description

${DESC}

## Context

Captured by retroonto-trace at ${TIMESTAMP}.

## Root Cause

_To be filled in post-hoc analysis._

## Resolution

_To be filled in after correction._

## Encoded Rule

_To be generated by constraint-gen.sh._
EOF

echo "✅ Archive entry created: ${ARCHIVE_FILE}"

# Write to DB
if command -v sqlite3 &>/dev/null; then
    sqlite3 "$DB" "
        INSERT INTO decision_traces (id, e0_raw_event, e1_classification, e2_derivation_chain, source_agent, category, severity)
        VALUES ('${ID}', '${DESC}', '${CATEGORY}', 'Captured via trace.sh', '${AGENT}', '${CATEGORY}', '${SEVERITY}');
    " 2>/dev/null && echo "✅ DB entry created: ${ID}" || echo "⚠️  DB write skipped (table may not exist)" 
fi

# Output-only mode returns the ID for piping
if $OUTPUT_ONLY; then
    echo "${ID}"
fi
