#!/usr/bin/env bash
# retroonto-writeback — Write constraint → permanent knowledge ring
# Usage: ./src/writeback.sh --trace-id ERR-xxx --target knowledge/constraint-name.md
set -euo pipefail

RETROONTO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DB="${RETROONTO_DIR}/retroonto.db"

TRACE_ID=""
TARGET=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --trace-id) TRACE_ID="$2"; shift 2 ;;
        --target) TARGET="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

if [[ -z "$TRACE_ID" || -z "$TARGET" ]]; then
    echo "Usage: $0 --trace-id ERR-xxx --target path/to/knowledge.md"
    exit 1
fi

ARCHIVE_DIR="${RETROONTO_DIR}/archive"
ARCHIVE_FILE=$(find "$ARCHIVE_DIR" -name "${TRACE_ID}.md" 2>/dev/null | head -1)

if [[ -z "$ARCHIVE_FILE" ]]; then
    echo "⚠️  Archive entry ${TRACE_ID}.md not found"
    exit 1
fi

echo "📝 Writing knowledge ring: ${TRACE_ID} → ${TARGET}"
mkdir -p "$(dirname "${TARGET}")"

cat > "$TARGET" << EOF
# ${TRACE_ID} — Auto-generated Knowledge Ring Writeback

**Source:** ${ARCHIVE_FILE}

---

$(cat "$ARCHIVE_FILE")

---

*Generated by retroonto-writeback at $(date -u +"%Y-%m-%dT%H:%M:%SZ")*
EOF

echo "✅ Writeback complete: ${TARGET}"

# Log to DB
if command -v sqlite3 &>/dev/null && [[ -f "$DB" ]]; then
    sqlite3 "$DB" "INSERT INTO writebacks (id, source_trace_id, target_path) VALUES ('WB-$(date +%s)', '${TRACE_ID}', '${TARGET}');" 2>/dev/null || true
fi
